/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AffiliateSearchMeta
    /// </summary>
    [DataContract]
    public partial class AffiliateSearchMeta :  IEquatable<AffiliateSearchMeta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AffiliateSearchMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AffiliateSearchMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AffiliateSearchMeta" /> class.
        /// </summary>
        /// <param name="Carriers">A map of meta information for each of the airlines involved in the response (required).</param>
        public AffiliateSearchMeta(CarrierMeta Carriers = default(CarrierMeta))
        {
            // to ensure "Carriers" is required (not null)
            if (Carriers == null)
            {
                throw new InvalidDataException("Carriers is a required property for AffiliateSearchMeta and cannot be null");
            }
            else
            {
                this.Carriers = Carriers;
            }
        }
        
        /// <summary>
        /// A map of meta information for each of the airlines involved in the response
        /// </summary>
        /// <value>A map of meta information for each of the airlines involved in the response</value>
        [DataMember(Name="carriers", EmitDefaultValue=false)]
        public CarrierMeta Carriers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AffiliateSearchMeta {\n");
            sb.Append("  Carriers: ").Append(Carriers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AffiliateSearchMeta);
        }

        /// <summary>
        /// Returns true if AffiliateSearchMeta instances are equal
        /// </summary>
        /// <param name="input">Instance of AffiliateSearchMeta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AffiliateSearchMeta input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Carriers == input.Carriers ||
                    (this.Carriers != null &&
                    this.Carriers.Equals(input.Carriers))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Carriers != null)
                    hashCode = hashCode * 59 + this.Carriers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
