/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AffiliatePayout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AffiliatePayoutTests
    {
        // TODO uncomment below to declare an instance variable for AffiliatePayout
        //private AffiliatePayout instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AffiliatePayout
            //instance = new AffiliatePayout();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AffiliatePayout
        /// </summary>
        [Test]
        public void AffiliatePayoutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AffiliatePayout
            //Assert.IsInstanceOfType<AffiliatePayout> (instance, "variable 'instance' is a AffiliatePayout");
        }


        /// <summary>
        /// Test the property 'CPC'
        /// </summary>
        [Test]
        public void CPCTest()
        {
            // TODO unit test for the property 'CPC'
        }
        /// <summary>
        /// Test the property 'CPA'
        /// </summary>
        [Test]
        public void CPATest()
        {
            // TODO unit test for the property 'CPA'
        }
        /// <summary>
        /// Test the property 'CPS'
        /// </summary>
        [Test]
        public void CPSTest()
        {
            // TODO unit test for the property 'CPS'
        }

    }

}
