/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AffiliateSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AffiliateSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for AffiliateSearchResult
        //private AffiliateSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AffiliateSearchResult
            //instance = new AffiliateSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AffiliateSearchResult
        /// </summary>
        [Test]
        public void AffiliateSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AffiliateSearchResult
            //Assert.IsInstanceOfType<AffiliateSearchResult> (instance, "variable 'instance' is a AffiliateSearchResult");
        }


        /// <summary>
        /// Test the property 'Outbound'
        /// </summary>
        [Test]
        public void OutboundTest()
        {
            // TODO unit test for the property 'Outbound'
        }
        /// <summary>
        /// Test the property 'Inbound'
        /// </summary>
        [Test]
        public void InboundTest()
        {
            // TODO unit test for the property 'Inbound'
        }
        /// <summary>
        /// Test the property 'Fare'
        /// </summary>
        [Test]
        public void FareTest()
        {
            // TODO unit test for the property 'Fare'
        }
        /// <summary>
        /// Test the property 'Payout'
        /// </summary>
        [Test]
        public void PayoutTest()
        {
            // TODO unit test for the property 'Payout'
        }
        /// <summary>
        /// Test the property 'Airline'
        /// </summary>
        [Test]
        public void AirlineTest()
        {
            // TODO unit test for the property 'Airline'
        }
        /// <summary>
        /// Test the property 'DeepLink'
        /// </summary>
        [Test]
        public void DeepLinkTest()
        {
            // TODO unit test for the property 'DeepLink'
        }

    }

}
