/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AffiliateFlightSearchPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AffiliateFlightSearchPriceTests
    {
        // TODO uncomment below to declare an instance variable for AffiliateFlightSearchPrice
        //private AffiliateFlightSearchPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AffiliateFlightSearchPrice
            //instance = new AffiliateFlightSearchPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AffiliateFlightSearchPrice
        /// </summary>
        [Test]
        public void AffiliateFlightSearchPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AffiliateFlightSearchPrice
            //Assert.IsInstanceOfType<AffiliateFlightSearchPrice> (instance, "variable 'instance' is a AffiliateFlightSearchPrice");
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'PricePerAdult'
        /// </summary>
        [Test]
        public void PricePerAdultTest()
        {
            // TODO unit test for the property 'PricePerAdult'
        }
        /// <summary>
        /// Test the property 'PricePerChild'
        /// </summary>
        [Test]
        public void PricePerChildTest()
        {
            // TODO unit test for the property 'PricePerChild'
        }
        /// <summary>
        /// Test the property 'PricePerInfant'
        /// </summary>
        [Test]
        public void PricePerInfantTest()
        {
            // TODO unit test for the property 'PricePerInfant'
        }
        /// <summary>
        /// Test the property 'Restrictions'
        /// </summary>
        [Test]
        public void RestrictionsTest()
        {
            // TODO unit test for the property 'Restrictions'
        }

    }

}
