/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Airport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AirportTests
    {
        // TODO uncomment below to declare an instance variable for Airport
        //private Airport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Airport
            //instance = new Airport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Airport
        /// </summary>
        [Test]
        public void AirportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Airport
            //Assert.IsInstanceOfType<Airport> (instance, "variable 'instance' is a Airport");
        }


        /// <summary>
        /// Test the property '_Airport'
        /// </summary>
        [Test]
        public void _AirportTest()
        {
            // TODO unit test for the property '_Airport'
        }
        /// <summary>
        /// Test the property 'Terminal'
        /// </summary>
        [Test]
        public void TerminalTest()
        {
            // TODO unit test for the property 'Terminal'
        }

    }

}
