/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Amenity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AmenityTests
    {
        // TODO uncomment below to declare an instance variable for Amenity
        //private Amenity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Amenity
            //instance = new Amenity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Amenity
        /// </summary>
        [Test]
        public void AmenityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Amenity
            //Assert.IsInstanceOfType<Amenity> (instance, "variable 'instance' is a Amenity");
        }


        /// <summary>
        /// Test the property '_Amenity'
        /// </summary>
        [Test]
        public void _AmenityTest()
        {
            // TODO unit test for the property '_Amenity'
        }
        /// <summary>
        /// Test the property 'OtaCode'
        /// </summary>
        [Test]
        public void OtaCodeTest()
        {
            // TODO unit test for the property 'OtaCode'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
