/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CarReservationBookingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarReservationBookingInfoTests
    {
        // TODO uncomment below to declare an instance variable for CarReservationBookingInfo
        //private CarReservationBookingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarReservationBookingInfo
            //instance = new CarReservationBookingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarReservationBookingInfo
        /// </summary>
        [Test]
        public void CarReservationBookingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarReservationBookingInfo
            //Assert.IsInstanceOfType<CarReservationBookingInfo> (instance, "variable 'instance' is a CarReservationBookingInfo");
        }


        /// <summary>
        /// Test the property 'ReservationCode'
        /// </summary>
        [Test]
        public void ReservationCodeTest()
        {
            // TODO unit test for the property 'ReservationCode'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
