/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CarrierInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarrierInfoTests
    {
        // TODO uncomment below to declare an instance variable for CarrierInfo
        //private CarrierInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierInfo
            //instance = new CarrierInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierInfo
        /// </summary>
        [Test]
        public void CarrierInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarrierInfo
            //Assert.IsInstanceOfType<CarrierInfo> (instance, "variable 'instance' is a CarrierInfo");
        }


        /// <summary>
        /// Test the property 'Logos'
        /// </summary>
        [Test]
        public void LogosTest()
        {
            // TODO unit test for the property 'Logos'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
