/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CarReservation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarReservationTests
    {
        // TODO uncomment below to declare an instance variable for CarReservation
        //private CarReservation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarReservation
            //instance = new CarReservation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarReservation
        /// </summary>
        [Test]
        public void CarReservationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarReservation
            //Assert.IsInstanceOfType<CarReservation> (instance, "variable 'instance' is a CarReservation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PickUp'
        /// </summary>
        [Test]
        public void PickUpTest()
        {
            // TODO unit test for the property 'PickUp'
        }
        /// <summary>
        /// Test the property 'DropOff'
        /// </summary>
        [Test]
        public void DropOffTest()
        {
            // TODO unit test for the property 'DropOff'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Car'
        /// </summary>
        [Test]
        public void CarTest()
        {
            // TODO unit test for the property 'Car'
        }
        /// <summary>
        /// Test the property 'TravelerIds'
        /// </summary>
        [Test]
        public void TravelerIdsTest()
        {
            // TODO unit test for the property 'TravelerIds'
        }
        /// <summary>
        /// Test the property 'BookingInfo'
        /// </summary>
        [Test]
        public void BookingInfoTest()
        {
            // TODO unit test for the property 'BookingInfo'
        }

    }

}
