/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtensiveTrainSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensiveTrainSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for ExtensiveTrainSearchResult
        //private ExtensiveTrainSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtensiveTrainSearchResult
            //instance = new ExtensiveTrainSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtensiveTrainSearchResult
        /// </summary>
        [Test]
        public void ExtensiveTrainSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtensiveTrainSearchResult
            //Assert.IsInstanceOfType<ExtensiveTrainSearchResult> (instance, "variable 'instance' is a ExtensiveTrainSearchResult");
        }


        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Itineraries'
        /// </summary>
        [Test]
        public void ItinerariesTest()
        {
            // TODO unit test for the property 'Itineraries'
        }

    }

}
