/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExtremeSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtremeSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for ExtremeSearchResult
        //private ExtremeSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtremeSearchResult
            //instance = new ExtremeSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtremeSearchResult
        /// </summary>
        [Test]
        public void ExtremeSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtremeSearchResult
            //Assert.IsInstanceOfType<ExtremeSearchResult> (instance, "variable 'instance' is a ExtremeSearchResult");
        }


        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'DepartureDate'
        /// </summary>
        [Test]
        public void DepartureDateTest()
        {
            // TODO unit test for the property 'DepartureDate'
        }
        /// <summary>
        /// Test the property 'ReturnDate'
        /// </summary>
        [Test]
        public void ReturnDateTest()
        {
            // TODO unit test for the property 'ReturnDate'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Airline'
        /// </summary>
        [Test]
        public void AirlineTest()
        {
            // TODO unit test for the property 'Airline'
        }

    }

}
