/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FareRestrictions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FareRestrictionsTests
    {
        // TODO uncomment below to declare an instance variable for FareRestrictions
        //private FareRestrictions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FareRestrictions
            //instance = new FareRestrictions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FareRestrictions
        /// </summary>
        [Test]
        public void FareRestrictionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FareRestrictions
            //Assert.IsInstanceOfType<FareRestrictions> (instance, "variable 'instance' is a FareRestrictions");
        }


        /// <summary>
        /// Test the property 'Refundable'
        /// </summary>
        [Test]
        public void RefundableTest()
        {
            // TODO unit test for the property 'Refundable'
        }
        /// <summary>
        /// Test the property 'ChangePenalties'
        /// </summary>
        [Test]
        public void ChangePenaltiesTest()
        {
            // TODO unit test for the property 'ChangePenalties'
        }

    }

}
