/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Fees
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeesTests
    {
        // TODO uncomment below to declare an instance variable for Fees
        //private Fees instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Fees
            //instance = new Fees();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Fees
        /// </summary>
        [Test]
        public void FeesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Fees
            //Assert.IsInstanceOfType<Fees> (instance, "variable 'instance' is a Fees");
        }


        /// <summary>
        /// Test the property 'ServiceFees'
        /// </summary>
        [Test]
        public void ServiceFeesTest()
        {
            // TODO unit test for the property 'ServiceFees'
        }
        /// <summary>
        /// Test the property 'CreditcardFees'
        /// </summary>
        [Test]
        public void CreditcardFeesTest()
        {
            // TODO unit test for the property 'CreditcardFees'
        }

    }

}
