/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightSearchBound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightSearchBoundTests
    {
        // TODO uncomment below to declare an instance variable for FlightSearchBound
        //private FlightSearchBound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightSearchBound
            //instance = new FlightSearchBound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightSearchBound
        /// </summary>
        [Test]
        public void FlightSearchBoundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightSearchBound
            //Assert.IsInstanceOfType<FlightSearchBound> (instance, "variable 'instance' is a FlightSearchBound");
        }


        /// <summary>
        /// Test the property 'Flights'
        /// </summary>
        [Test]
        public void FlightsTest()
        {
            // TODO unit test for the property 'Flights'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
