/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightReservationBookingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightReservationBookingInfoTests
    {
        // TODO uncomment below to declare an instance variable for FlightReservationBookingInfo
        //private FlightReservationBookingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightReservationBookingInfo
            //instance = new FlightReservationBookingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightReservationBookingInfo
        /// </summary>
        [Test]
        public void FlightReservationBookingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightReservationBookingInfo
            //Assert.IsInstanceOfType<FlightReservationBookingInfo> (instance, "variable 'instance' is a FlightReservationBookingInfo");
        }


        /// <summary>
        /// Test the property 'TravelClass'
        /// </summary>
        [Test]
        public void TravelClassTest()
        {
            // TODO unit test for the property 'TravelClass'
        }
        /// <summary>
        /// Test the property 'BookingCode'
        /// </summary>
        [Test]
        public void BookingCodeTest()
        {
            // TODO unit test for the property 'BookingCode'
        }
        /// <summary>
        /// Test the property 'AirlineRecordLocator'
        /// </summary>
        [Test]
        public void AirlineRecordLocatorTest()
        {
            // TODO unit test for the property 'AirlineRecordLocator'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
