/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightTicket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightTicketTests
    {
        // TODO uncomment below to declare an instance variable for FlightTicket
        //private FlightTicket instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightTicket
            //instance = new FlightTicket();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightTicket
        /// </summary>
        [Test]
        public void FlightTicketInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightTicket
            //Assert.IsInstanceOfType<FlightTicket> (instance, "variable 'instance' is a FlightTicket");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'TravelerIds'
        /// </summary>
        [Test]
        public void TravelerIdsTest()
        {
            // TODO unit test for the property 'TravelerIds'
        }
        /// <summary>
        /// Test the property 'FlightBounds'
        /// </summary>
        [Test]
        public void FlightBoundsTest()
        {
            // TODO unit test for the property 'FlightBounds'
        }

    }

}
