/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightSearchPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightSearchPriceTests
    {
        // TODO uncomment below to declare an instance variable for FlightSearchPrice
        //private FlightSearchPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightSearchPrice
            //instance = new FlightSearchPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightSearchPrice
        /// </summary>
        [Test]
        public void FlightSearchPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightSearchPrice
            //Assert.IsInstanceOfType<FlightSearchPrice> (instance, "variable 'instance' is a FlightSearchPrice");
        }


        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'PricePerAdult'
        /// </summary>
        [Test]
        public void PricePerAdultTest()
        {
            // TODO unit test for the property 'PricePerAdult'
        }
        /// <summary>
        /// Test the property 'PricePerChild'
        /// </summary>
        [Test]
        public void PricePerChildTest()
        {
            // TODO unit test for the property 'PricePerChild'
        }
        /// <summary>
        /// Test the property 'PricePerInfant'
        /// </summary>
        [Test]
        public void PricePerInfantTest()
        {
            // TODO unit test for the property 'PricePerInfant'
        }
        /// <summary>
        /// Test the property 'Restrictions'
        /// </summary>
        [Test]
        public void RestrictionsTest()
        {
            // TODO unit test for the property 'Restrictions'
        }

    }

}
