/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightSearchItinerary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightSearchItineraryTests
    {
        // TODO uncomment below to declare an instance variable for FlightSearchItinerary
        //private FlightSearchItinerary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightSearchItinerary
            //instance = new FlightSearchItinerary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightSearchItinerary
        /// </summary>
        [Test]
        public void FlightSearchItineraryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightSearchItinerary
            //Assert.IsInstanceOfType<FlightSearchItinerary> (instance, "variable 'instance' is a FlightSearchItinerary");
        }


        /// <summary>
        /// Test the property 'Outbound'
        /// </summary>
        [Test]
        public void OutboundTest()
        {
            // TODO unit test for the property 'Outbound'
        }
        /// <summary>
        /// Test the property 'Inbound'
        /// </summary>
        [Test]
        public void InboundTest()
        {
            // TODO unit test for the property 'Inbound'
        }

    }

}
