/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightReservationSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightReservationSegmentTests
    {
        // TODO uncomment below to declare an instance variable for FlightReservationSegment
        //private FlightReservationSegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightReservationSegment
            //instance = new FlightReservationSegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightReservationSegment
        /// </summary>
        [Test]
        public void FlightReservationSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightReservationSegment
            //Assert.IsInstanceOfType<FlightReservationSegment> (instance, "variable 'instance' is a FlightReservationSegment");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DepartsAt'
        /// </summary>
        [Test]
        public void DepartsAtTest()
        {
            // TODO unit test for the property 'DepartsAt'
        }
        /// <summary>
        /// Test the property 'ArrivesAt'
        /// </summary>
        [Test]
        public void ArrivesAtTest()
        {
            // TODO unit test for the property 'ArrivesAt'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'MarketingAirline'
        /// </summary>
        [Test]
        public void MarketingAirlineTest()
        {
            // TODO unit test for the property 'MarketingAirline'
        }
        /// <summary>
        /// Test the property 'OperatingAirline'
        /// </summary>
        [Test]
        public void OperatingAirlineTest()
        {
            // TODO unit test for the property 'OperatingAirline'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Test]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }
        /// <summary>
        /// Test the property 'TravelerIds'
        /// </summary>
        [Test]
        public void TravelerIdsTest()
        {
            // TODO unit test for the property 'TravelerIds'
        }
        /// <summary>
        /// Test the property 'BookingInfo'
        /// </summary>
        [Test]
        public void BookingInfoTest()
        {
            // TODO unit test for the property 'BookingInfo'
        }

    }

}
