/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightTrafficSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightTrafficSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for FlightTrafficSearchResult
        //private FlightTrafficSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightTrafficSearchResult
            //instance = new FlightTrafficSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightTrafficSearchResult
        /// </summary>
        [Test]
        public void FlightTrafficSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightTrafficSearchResult
            //Assert.IsInstanceOfType<FlightTrafficSearchResult> (instance, "variable 'instance' is a FlightTrafficSearchResult");
        }


        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Flights'
        /// </summary>
        [Test]
        public void FlightsTest()
        {
            // TODO unit test for the property 'Flights'
        }
        /// <summary>
        /// Test the property 'Travelers'
        /// </summary>
        [Test]
        public void TravelersTest()
        {
            // TODO unit test for the property 'Travelers'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

    }

}
