/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightReservationBound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightReservationBoundTests
    {
        // TODO uncomment below to declare an instance variable for FlightReservationBound
        //private FlightReservationBound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightReservationBound
            //instance = new FlightReservationBound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightReservationBound
        /// </summary>
        [Test]
        public void FlightReservationBoundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightReservationBound
            //Assert.IsInstanceOfType<FlightReservationBound> (instance, "variable 'instance' is a FlightReservationBound");
        }


        /// <summary>
        /// Test the property 'Flights'
        /// </summary>
        [Test]
        public void FlightsTest()
        {
            // TODO unit test for the property 'Flights'
        }

    }

}
