/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightSearchBookingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightSearchBookingInfoTests
    {
        // TODO uncomment below to declare an instance variable for FlightSearchBookingInfo
        //private FlightSearchBookingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightSearchBookingInfo
            //instance = new FlightSearchBookingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightSearchBookingInfo
        /// </summary>
        [Test]
        public void FlightSearchBookingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightSearchBookingInfo
            //Assert.IsInstanceOfType<FlightSearchBookingInfo> (instance, "variable 'instance' is a FlightSearchBookingInfo");
        }


        /// <summary>
        /// Test the property 'TravelClass'
        /// </summary>
        [Test]
        public void TravelClassTest()
        {
            // TODO unit test for the property 'TravelClass'
        }
        /// <summary>
        /// Test the property 'CabinCode'
        /// </summary>
        [Test]
        public void CabinCodeTest()
        {
            // TODO unit test for the property 'CabinCode'
        }
        /// <summary>
        /// Test the property 'BookingCode'
        /// </summary>
        [Test]
        public void BookingCodeTest()
        {
            // TODO unit test for the property 'BookingCode'
        }
        /// <summary>
        /// Test the property 'SeatsRemaining'
        /// </summary>
        [Test]
        public void SeatsRemainingTest()
        {
            // TODO unit test for the property 'SeatsRemaining'
        }
        /// <summary>
        /// Test the property 'FareFamily'
        /// </summary>
        [Test]
        public void FareFamilyTest()
        {
            // TODO unit test for the property 'FareFamily'
        }
        /// <summary>
        /// Test the property 'FareBasis'
        /// </summary>
        [Test]
        public void FareBasisTest()
        {
            // TODO unit test for the property 'FareBasis'
        }

    }

}
