/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FrequentTravelerCard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FrequentTravelerCardTests
    {
        // TODO uncomment below to declare an instance variable for FrequentTravelerCard
        //private FrequentTravelerCard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FrequentTravelerCard
            //instance = new FrequentTravelerCard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FrequentTravelerCard
        /// </summary>
        [Test]
        public void FrequentTravelerCardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FrequentTravelerCard
            //Assert.IsInstanceOfType<FrequentTravelerCard> (instance, "variable 'instance' is a FrequentTravelerCard");
        }


        /// <summary>
        /// Test the property 'IssuerType'
        /// </summary>
        [Test]
        public void IssuerTypeTest()
        {
            // TODO unit test for the property 'IssuerType'
        }
        /// <summary>
        /// Test the property 'CompanyCode'
        /// </summary>
        [Test]
        public void CompanyCodeTest()
        {
            // TODO unit test for the property 'CompanyCode'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }

    }

}
