/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelPropertyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelPropertyResponseTests
    {
        // TODO uncomment below to declare an instance variable for HotelPropertyResponse
        //private HotelPropertyResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelPropertyResponse
            //instance = new HotelPropertyResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelPropertyResponse
        /// </summary>
        [Test]
        public void HotelPropertyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelPropertyResponse
            //Assert.IsInstanceOfType<HotelPropertyResponse> (instance, "variable 'instance' is a HotelPropertyResponse");
        }


        /// <summary>
        /// Test the property 'PropertyCode'
        /// </summary>
        [Test]
        public void PropertyCodeTest()
        {
            // TODO unit test for the property 'PropertyCode'
        }
        /// <summary>
        /// Test the property 'PropertyName'
        /// </summary>
        [Test]
        public void PropertyNameTest()
        {
            // TODO unit test for the property 'PropertyName'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'MinDailyRate'
        /// </summary>
        [Test]
        public void MinDailyRateTest()
        {
            // TODO unit test for the property 'MinDailyRate'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Test]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'Amenities'
        /// </summary>
        [Test]
        public void AmenitiesTest()
        {
            // TODO unit test for the property 'Amenities'
        }
        /// <summary>
        /// Test the property 'Awards'
        /// </summary>
        [Test]
        public void AwardsTest()
        {
            // TODO unit test for the property 'Awards'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Rooms'
        /// </summary>
        [Test]
        public void RoomsTest()
        {
            // TODO unit test for the property 'Rooms'
        }
        /// <summary>
        /// Test the property 'MoreRoomsAtThisHotel'
        /// </summary>
        [Test]
        public void MoreRoomsAtThisHotelTest()
        {
            // TODO unit test for the property 'MoreRoomsAtThisHotel'
        }

    }

}
