/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelReservation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelReservationTests
    {
        // TODO uncomment below to declare an instance variable for HotelReservation
        //private HotelReservation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelReservation
            //instance = new HotelReservation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelReservation
        /// </summary>
        [Test]
        public void HotelReservationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelReservation
            //Assert.IsInstanceOfType<HotelReservation> (instance, "variable 'instance' is a HotelReservation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CheckIn'
        /// </summary>
        [Test]
        public void CheckInTest()
        {
            // TODO unit test for the property 'CheckIn'
        }
        /// <summary>
        /// Test the property 'CheckOut'
        /// </summary>
        [Test]
        public void CheckOutTest()
        {
            // TODO unit test for the property 'CheckOut'
        }
        /// <summary>
        /// Test the property 'PropertyCode'
        /// </summary>
        [Test]
        public void PropertyCodeTest()
        {
            // TODO unit test for the property 'PropertyCode'
        }
        /// <summary>
        /// Test the property 'PropertyName'
        /// </summary>
        [Test]
        public void PropertyNameTest()
        {
            // TODO unit test for the property 'PropertyName'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'TravelerIds'
        /// </summary>
        [Test]
        public void TravelerIdsTest()
        {
            // TODO unit test for the property 'TravelerIds'
        }
        /// <summary>
        /// Test the property 'BookingInfo'
        /// </summary>
        [Test]
        public void BookingInfoTest()
        {
            // TODO unit test for the property 'BookingInfo'
        }

    }

}
