/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelRoom
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelRoomTests
    {
        // TODO uncomment below to declare an instance variable for HotelRoom
        //private HotelRoom instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelRoom
            //instance = new HotelRoom();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelRoom
        /// </summary>
        [Test]
        public void HotelRoomInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelRoom
            //Assert.IsInstanceOfType<HotelRoom> (instance, "variable 'instance' is a HotelRoom");
        }


        /// <summary>
        /// Test the property 'BookingCode'
        /// </summary>
        [Test]
        public void BookingCodeTest()
        {
            // TODO unit test for the property 'BookingCode'
        }
        /// <summary>
        /// Test the property 'RoomTypeCode'
        /// </summary>
        [Test]
        public void RoomTypeCodeTest()
        {
            // TODO unit test for the property 'RoomTypeCode'
        }
        /// <summary>
        /// Test the property 'RatePlanCode'
        /// </summary>
        [Test]
        public void RatePlanCodeTest()
        {
            // TODO unit test for the property 'RatePlanCode'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Test]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'Descriptions'
        /// </summary>
        [Test]
        public void DescriptionsTest()
        {
            // TODO unit test for the property 'Descriptions'
        }
        /// <summary>
        /// Test the property 'RoomTypeInfo'
        /// </summary>
        [Test]
        public void RoomTypeInfoTest()
        {
            // TODO unit test for the property 'RoomTypeInfo'
        }
        /// <summary>
        /// Test the property 'RateTypeCode'
        /// </summary>
        [Test]
        public void RateTypeCodeTest()
        {
            // TODO unit test for the property 'RateTypeCode'
        }

    }

}
