/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ImageSize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImageSizeTests
    {
        // TODO uncomment below to declare an instance variable for ImageSize
        //private ImageSize instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ImageSize
            //instance = new ImageSize();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImageSize
        /// </summary>
        [Test]
        public void ImageSizeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ImageSize
            //Assert.IsInstanceOfType<ImageSize> (instance, "variable 'instance' is a ImageSize");
        }


        /// <summary>
        /// Test the property 'Small'
        /// </summary>
        [Test]
        public void SmallTest()
        {
            // TODO unit test for the property 'Small'
        }
        /// <summary>
        /// Test the property 'Medium'
        /// </summary>
        [Test]
        public void MediumTest()
        {
            // TODO unit test for the property 'Medium'
        }
        /// <summary>
        /// Test the property 'Large'
        /// </summary>
        [Test]
        public void LargeTest()
        {
            // TODO unit test for the property 'Large'
        }
        /// <summary>
        /// Test the property 'Hd'
        /// </summary>
        [Test]
        public void HdTest()
        {
            // TODO unit test for the property 'Hd'
        }

    }

}
