/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Logos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogosTests
    {
        // TODO uncomment below to declare an instance variable for Logos
        //private Logos instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Logos
            //instance = new Logos();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Logos
        /// </summary>
        [Test]
        public void LogosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Logos
            //Assert.IsInstanceOfType<Logos> (instance, "variable 'instance' is a Logos");
        }


        /// <summary>
        /// Test the property 'Small'
        /// </summary>
        [Test]
        public void SmallTest()
        {
            // TODO unit test for the property 'Small'
        }
        /// <summary>
        /// Test the property 'Medium'
        /// </summary>
        [Test]
        public void MediumTest()
        {
            // TODO unit test for the property 'Medium'
        }

    }

}
