/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LowFareSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LowFareSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for LowFareSearchResult
        //private LowFareSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LowFareSearchResult
            //instance = new LowFareSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LowFareSearchResult
        /// </summary>
        [Test]
        public void LowFareSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LowFareSearchResult
            //Assert.IsInstanceOfType<LowFareSearchResult> (instance, "variable 'instance' is a LowFareSearchResult");
        }


        /// <summary>
        /// Test the property 'Itineraries'
        /// </summary>
        [Test]
        public void ItinerariesTest()
        {
            // TODO unit test for the property 'Itineraries'
        }
        /// <summary>
        /// Test the property 'Fare'
        /// </summary>
        [Test]
        public void FareTest()
        {
            // TODO unit test for the property 'Fare'
        }

    }

}
