/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NearestAirport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NearestAirportTests
    {
        // TODO uncomment below to declare an instance variable for NearestAirport
        //private NearestAirport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NearestAirport
            //instance = new NearestAirport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NearestAirport
        /// </summary>
        [Test]
        public void NearestAirportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NearestAirport
            //Assert.IsInstanceOfType<NearestAirport> (instance, "variable 'instance' is a NearestAirport");
        }


        /// <summary>
        /// Test the property 'Airport'
        /// </summary>
        [Test]
        public void AirportTest()
        {
            // TODO unit test for the property 'Airport'
        }
        /// <summary>
        /// Test the property 'AirportName'
        /// </summary>
        [Test]
        public void AirportNameTest()
        {
            // TODO unit test for the property 'AirportName'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Test]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'AircraftMovements'
        /// </summary>
        [Test]
        public void AircraftMovementsTest()
        {
            // TODO unit test for the property 'AircraftMovements'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
