/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PointOfInterestDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointOfInterestDetailsTests
    {
        // TODO uncomment below to declare an instance variable for PointOfInterestDetails
        //private PointOfInterestDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PointOfInterestDetails
            //instance = new PointOfInterestDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PointOfInterestDetails
        /// </summary>
        [Test]
        public void PointOfInterestDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PointOfInterestDetails
            //Assert.IsInstanceOfType<PointOfInterestDetails> (instance, "variable 'instance' is a PointOfInterestDetails");
        }


        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Test]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'WikiPageLink'
        /// </summary>
        [Test]
        public void WikiPageLinkTest()
        {
            // TODO unit test for the property 'WikiPageLink'
        }

    }

}
