/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PointsOfInterestResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointsOfInterestResponseTests
    {
        // TODO uncomment below to declare an instance variable for PointsOfInterestResponse
        //private PointsOfInterestResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PointsOfInterestResponse
            //instance = new PointsOfInterestResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PointsOfInterestResponse
        /// </summary>
        [Test]
        public void PointsOfInterestResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PointsOfInterestResponse
            //Assert.IsInstanceOfType<PointsOfInterestResponse> (instance, "variable 'instance' is a PointsOfInterestResponse");
        }


        /// <summary>
        /// Test the property 'CurrentCity'
        /// </summary>
        [Test]
        public void CurrentCityTest()
        {
            // TODO unit test for the property 'CurrentCity'
        }
        /// <summary>
        /// Test the property 'PointsOfInterest'
        /// </summary>
        [Test]
        public void PointsOfInterestTest()
        {
            // TODO unit test for the property 'PointsOfInterest'
        }

    }

}
