/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PointOfInterestCity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointOfInterestCityTests
    {
        // TODO uncomment below to declare an instance variable for PointOfInterestCity
        //private PointOfInterestCity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PointOfInterestCity
            //instance = new PointOfInterestCity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PointOfInterestCity
        /// </summary>
        [Test]
        public void PointOfInterestCityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PointOfInterestCity
            //Assert.IsInstanceOfType<PointOfInterestCity> (instance, "variable 'instance' is a PointOfInterestCity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'GeonameId'
        /// </summary>
        [Test]
        public void GeonameIdTest()
        {
            // TODO unit test for the property 'GeonameId'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'TotalPointsOfInterest'
        /// </summary>
        [Test]
        public void TotalPointsOfInterestTest()
        {
            // TODO unit test for the property 'TotalPointsOfInterest'
        }

    }

}
