/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PointOfInterestResultGrades
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointOfInterestResultGradesTests
    {
        // TODO uncomment below to declare an instance variable for PointOfInterestResultGrades
        //private PointOfInterestResultGrades instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PointOfInterestResultGrades
            //instance = new PointOfInterestResultGrades();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PointOfInterestResultGrades
        /// </summary>
        [Test]
        public void PointOfInterestResultGradesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PointOfInterestResultGrades
            //Assert.IsInstanceOfType<PointOfInterestResultGrades> (instance, "variable 'instance' is a PointOfInterestResultGrades");
        }


        /// <summary>
        /// Test the property 'YapqGrade'
        /// </summary>
        [Test]
        public void YapqGradeTest()
        {
            // TODO unit test for the property 'YapqGrade'
        }
        /// <summary>
        /// Test the property 'CityGrade'
        /// </summary>
        [Test]
        public void CityGradeTest()
        {
            // TODO unit test for the property 'CityGrade'
        }

    }

}
