/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PointOfInterestResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointOfInterestResultTests
    {
        // TODO uncomment below to declare an instance variable for PointOfInterestResult
        //private PointOfInterestResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PointOfInterestResult
            //instance = new PointOfInterestResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PointOfInterestResult
        /// </summary>
        [Test]
        public void PointOfInterestResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PointOfInterestResult
            //Assert.IsInstanceOfType<PointOfInterestResult> (instance, "variable 'instance' is a PointOfInterestResult");
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'MainImage'
        /// </summary>
        [Test]
        public void MainImageTest()
        {
            // TODO unit test for the property 'MainImage'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Grades'
        /// </summary>
        [Test]
        public void GradesTest()
        {
            // TODO unit test for the property 'Grades'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'ContextualImages'
        /// </summary>
        [Test]
        public void ContextualImagesTest()
        {
            // TODO unit test for the property 'ContextualImages'
        }
        /// <summary>
        /// Test the property 'GeonameId'
        /// </summary>
        [Test]
        public void GeonameIdTest()
        {
            // TODO unit test for the property 'GeonameId'
        }
        /// <summary>
        /// Test the property 'WalkTime'
        /// </summary>
        [Test]
        public void WalkTimeTest()
        {
            // TODO unit test for the property 'WalkTime'
        }

    }

}
