/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Reservation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReservationTests
    {
        // TODO uncomment below to declare an instance variable for Reservation
        //private Reservation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Reservation
            //instance = new Reservation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Reservation
        /// </summary>
        [Test]
        public void ReservationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Reservation
            //Assert.IsInstanceOfType<Reservation> (instance, "variable 'instance' is a Reservation");
        }


        /// <summary>
        /// Test the property 'FlightTickets'
        /// </summary>
        [Test]
        public void FlightTicketsTest()
        {
            // TODO unit test for the property 'FlightTickets'
        }
        /// <summary>
        /// Test the property 'UnticketedFlights'
        /// </summary>
        [Test]
        public void UnticketedFlightsTest()
        {
            // TODO unit test for the property 'UnticketedFlights'
        }
        /// <summary>
        /// Test the property 'Cars'
        /// </summary>
        [Test]
        public void CarsTest()
        {
            // TODO unit test for the property 'Cars'
        }
        /// <summary>
        /// Test the property 'Hotels'
        /// </summary>
        [Test]
        public void HotelsTest()
        {
            // TODO unit test for the property 'Hotels'
        }
        /// <summary>
        /// Test the property 'Others'
        /// </summary>
        [Test]
        public void OthersTest()
        {
            // TODO unit test for the property 'Others'
        }

    }

}
