/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RestrictedRate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestrictedRateTests
    {
        // TODO uncomment below to declare an instance variable for RestrictedRate
        //private RestrictedRate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestrictedRate
            //instance = new RestrictedRate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestrictedRate
        /// </summary>
        [Test]
        public void RestrictedRateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestrictedRate
            //Assert.IsInstanceOfType<RestrictedRate> (instance, "variable 'instance' is a RestrictedRate");
        }


        /// <summary>
        /// Test the property 'RateCode'
        /// </summary>
        [Test]
        public void RateCodeTest()
        {
            // TODO unit test for the property 'RateCode'
        }
        /// <summary>
        /// Test the property 'RateName'
        /// </summary>
        [Test]
        public void RateNameTest()
        {
            // TODO unit test for the property 'RateName'
        }
        /// <summary>
        /// Test the property 'Restrictions'
        /// </summary>
        [Test]
        public void RestrictionsTest()
        {
            // TODO unit test for the property 'Restrictions'
        }

    }

}
