/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RoomInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RoomInfoTests
    {
        // TODO uncomment below to declare an instance variable for RoomInfo
        //private RoomInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RoomInfo
            //instance = new RoomInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoomInfo
        /// </summary>
        [Test]
        public void RoomInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RoomInfo
            //Assert.IsInstanceOfType<RoomInfo> (instance, "variable 'instance' is a RoomInfo");
        }


        /// <summary>
        /// Test the property 'BedType'
        /// </summary>
        [Test]
        public void BedTypeTest()
        {
            // TODO unit test for the property 'BedType'
        }
        /// <summary>
        /// Test the property 'NumberOfBeds'
        /// </summary>
        [Test]
        public void NumberOfBedsTest()
        {
            // TODO unit test for the property 'NumberOfBeds'
        }
        /// <summary>
        /// Test the property 'RoomType'
        /// </summary>
        [Test]
        public void RoomTypeTest()
        {
            // TODO unit test for the property 'RoomType'
        }

    }

}
