/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Station
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StationTests
    {
        // TODO uncomment below to declare an instance variable for Station
        //private Station instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Station
            //instance = new Station();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Station
        /// </summary>
        [Test]
        public void StationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Station
            //Assert.IsInstanceOfType<Station> (instance, "variable 'instance' is a Station");
        }


        /// <summary>
        /// Test the property 'StationCode'
        /// </summary>
        [Test]
        public void StationCodeTest()
        {
            // TODO unit test for the property 'StationCode'
        }
        /// <summary>
        /// Test the property 'StationName'
        /// </summary>
        [Test]
        public void StationNameTest()
        {
            // TODO unit test for the property 'StationName'
        }

    }

}
