/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TopSearchesSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TopSearchesSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for TopSearchesSearchResult
        //private TopSearchesSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TopSearchesSearchResult
            //instance = new TopSearchesSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TopSearchesSearchResult
        /// </summary>
        [Test]
        public void TopSearchesSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TopSearchesSearchResult
            //Assert.IsInstanceOfType<TopSearchesSearchResult> (instance, "variable 'instance' is a TopSearchesSearchResult");
        }


        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Searches'
        /// </summary>
        [Test]
        public void SearchesTest()
        {
            // TODO unit test for the property 'Searches'
        }
        /// <summary>
        /// Test the property 'SearchesPriorYear'
        /// </summary>
        [Test]
        public void SearchesPriorYearTest()
        {
            // TODO unit test for the property 'SearchesPriorYear'
        }

    }

}
