/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrainScheduleSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrainScheduleSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for TrainScheduleSearchResult
        //private TrainScheduleSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrainScheduleSearchResult
            //instance = new TrainScheduleSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrainScheduleSearchResult
        /// </summary>
        [Test]
        public void TrainScheduleSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrainScheduleSearchResult
            //Assert.IsInstanceOfType<TrainScheduleSearchResult> (instance, "variable 'instance' is a TrainScheduleSearchResult");
        }


        /// <summary>
        /// Test the property 'OriginStationId'
        /// </summary>
        [Test]
        public void OriginStationIdTest()
        {
            // TODO unit test for the property 'OriginStationId'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

    }

}
