/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrainScheduleSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrainScheduleSearchResponseTests
    {
        // TODO uncomment below to declare an instance variable for TrainScheduleSearchResponse
        //private TrainScheduleSearchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrainScheduleSearchResponse
            //instance = new TrainScheduleSearchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrainScheduleSearchResponse
        /// </summary>
        [Test]
        public void TrainScheduleSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrainScheduleSearchResponse
            //Assert.IsInstanceOfType<TrainScheduleSearchResponse> (instance, "variable 'instance' is a TrainScheduleSearchResponse");
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
