/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrainSearchSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrainSearchSegmentTests
    {
        // TODO uncomment below to declare an instance variable for TrainSearchSegment
        //private TrainSearchSegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrainSearchSegment
            //instance = new TrainSearchSegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrainSearchSegment
        /// </summary>
        [Test]
        public void TrainSearchSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrainSearchSegment
            //Assert.IsInstanceOfType<TrainSearchSegment> (instance, "variable 'instance' is a TrainSearchSegment");
        }


        /// <summary>
        /// Test the property 'DepartsAt'
        /// </summary>
        [Test]
        public void DepartsAtTest()
        {
            // TODO unit test for the property 'DepartsAt'
        }
        /// <summary>
        /// Test the property 'ArrivesAt'
        /// </summary>
        [Test]
        public void ArrivesAtTest()
        {
            // TODO unit test for the property 'ArrivesAt'
        }
        /// <summary>
        /// Test the property 'DepartureStation'
        /// </summary>
        [Test]
        public void DepartureStationTest()
        {
            // TODO unit test for the property 'DepartureStation'
        }
        /// <summary>
        /// Test the property 'ArrivalStation'
        /// </summary>
        [Test]
        public void ArrivalStationTest()
        {
            // TODO unit test for the property 'ArrivalStation'
        }
        /// <summary>
        /// Test the property 'MarketingCompany'
        /// </summary>
        [Test]
        public void MarketingCompanyTest()
        {
            // TODO unit test for the property 'MarketingCompany'
        }
        /// <summary>
        /// Test the property 'OperatingCompany'
        /// </summary>
        [Test]
        public void OperatingCompanyTest()
        {
            // TODO unit test for the property 'OperatingCompany'
        }
        /// <summary>
        /// Test the property 'TrainNumber'
        /// </summary>
        [Test]
        public void TrainNumberTest()
        {
            // TODO unit test for the property 'TrainNumber'
        }
        /// <summary>
        /// Test the property 'TrainType'
        /// </summary>
        [Test]
        public void TrainTypeTest()
        {
            // TODO unit test for the property 'TrainType'
        }
        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Test]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }

    }

}
