/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TravelRecordHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TravelRecordHeaderTests
    {
        // TODO uncomment below to declare an instance variable for TravelRecordHeader
        //private TravelRecordHeader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TravelRecordHeader
            //instance = new TravelRecordHeader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TravelRecordHeader
        /// </summary>
        [Test]
        public void TravelRecordHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TravelRecordHeader
            //Assert.IsInstanceOfType<TravelRecordHeader> (instance, "variable 'instance' is a TravelRecordHeader");
        }


        /// <summary>
        /// Test the property 'CreationOfficeId'
        /// </summary>
        [Test]
        public void CreationOfficeIdTest()
        {
            // TODO unit test for the property 'CreationOfficeId'
        }
        /// <summary>
        /// Test the property 'OwnerOfficeId'
        /// </summary>
        [Test]
        public void OwnerOfficeIdTest()
        {
            // TODO unit test for the property 'OwnerOfficeId'
        }

    }

}
