/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TravelRecordResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TravelRecordResponseTests
    {
        // TODO uncomment below to declare an instance variable for TravelRecordResponse
        //private TravelRecordResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TravelRecordResponse
            //instance = new TravelRecordResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TravelRecordResponse
        /// </summary>
        [Test]
        public void TravelRecordResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TravelRecordResponse
            //Assert.IsInstanceOfType<TravelRecordResponse> (instance, "variable 'instance' is a TravelRecordResponse");
        }


        /// <summary>
        /// Test the property 'RecordLocator'
        /// </summary>
        [Test]
        public void RecordLocatorTest()
        {
            // TODO unit test for the property 'RecordLocator'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'Travelers'
        /// </summary>
        [Test]
        public void TravelersTest()
        {
            // TODO unit test for the property 'Travelers'
        }
        /// <summary>
        /// Test the property 'Reservation'
        /// </summary>
        [Test]
        public void ReservationTest()
        {
            // TODO unit test for the property 'Reservation'
        }

    }

}
