/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VehicleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleInfoTests
    {
        // TODO uncomment below to declare an instance variable for VehicleInfo
        //private VehicleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VehicleInfo
            //instance = new VehicleInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehicleInfo
        /// </summary>
        [Test]
        public void VehicleInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VehicleInfo
            //Assert.IsInstanceOfType<VehicleInfo> (instance, "variable 'instance' is a VehicleInfo");
        }


        /// <summary>
        /// Test the property 'AcrissCode'
        /// </summary>
        [Test]
        public void AcrissCodeTest()
        {
            // TODO unit test for the property 'AcrissCode'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Transmission'
        /// </summary>
        [Test]
        public void TransmissionTest()
        {
            // TODO unit test for the property 'Transmission'
        }
        /// <summary>
        /// Test the property 'AirConditioning'
        /// </summary>
        [Test]
        public void AirConditioningTest()
        {
            // TODO unit test for the property 'AirConditioning'
        }
        /// <summary>
        /// Test the property 'Fuel'
        /// </summary>
        [Test]
        public void FuelTest()
        {
            // TODO unit test for the property 'Fuel'
        }

    }

}
