/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Vehicle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleTests
    {
        // TODO uncomment below to declare an instance variable for Vehicle
        //private Vehicle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Vehicle
            //instance = new Vehicle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Vehicle
        /// </summary>
        [Test]
        public void VehicleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Vehicle
            //Assert.IsInstanceOfType<Vehicle> (instance, "variable 'instance' is a Vehicle");
        }


        /// <summary>
        /// Test the property 'VehicleInfo'
        /// </summary>
        [Test]
        public void VehicleInfoTest()
        {
            // TODO unit test for the property 'VehicleInfo'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'EstimatedTotal'
        /// </summary>
        [Test]
        public void EstimatedTotalTest()
        {
            // TODO unit test for the property 'EstimatedTotal'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

    }

}
