/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Fees
    /// </summary>
    [DataContract]
    public partial class Fees :  IEquatable<Fees>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Fees" /> class.
        /// </summary>
        /// <param name="ServiceFees">The cost of any required service fees in addition to the total price.</param>
        /// <param name="CreditcardFees">The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price.</param>
        public Fees(string ServiceFees = default(string), string CreditcardFees = default(string))
        {
            this.ServiceFees = ServiceFees;
            this.CreditcardFees = CreditcardFees;
        }
        
        /// <summary>
        /// The cost of any required service fees in addition to the total price
        /// </summary>
        /// <value>The cost of any required service fees in addition to the total price</value>
        [DataMember(Name="service_fees", EmitDefaultValue=false)]
        public string ServiceFees { get; set; }

        /// <summary>
        /// The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price
        /// </summary>
        /// <value>The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price</value>
        [DataMember(Name="creditcard_fees", EmitDefaultValue=false)]
        public string CreditcardFees { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Fees {\n");
            sb.Append("  ServiceFees: ").Append(ServiceFees).Append("\n");
            sb.Append("  CreditcardFees: ").Append(CreditcardFees).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Fees);
        }

        /// <summary>
        /// Returns true if Fees instances are equal
        /// </summary>
        /// <param name="input">Instance of Fees to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Fees input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServiceFees == input.ServiceFees ||
                    (this.ServiceFees != null &&
                    this.ServiceFees.Equals(input.ServiceFees))
                ) && 
                (
                    this.CreditcardFees == input.CreditcardFees ||
                    (this.CreditcardFees != null &&
                    this.CreditcardFees.Equals(input.CreditcardFees))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServiceFees != null)
                    hashCode = hashCode * 59 + this.ServiceFees.GetHashCode();
                if (this.CreditcardFees != null)
                    hashCode = hashCode * 59 + this.CreditcardFees.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
